### ISSUE TITLE
flipper doesn't invert

### ISSUE THREAD

**Issue by devanshi28** [jackparmer/colorlover#15]
Nice library- but I find that flipper doesn't really invert the colours. 

![screen shot 2017-11-09 at 16 49 13](https://user-images.githubusercontent.com/12432851/32617831-fa81cec0-c56d-11e7-8631-33ca1fb3bb4b.png)

**Comment by jonmmease** [comment]
Hi @devanshi28 ,

the `flipper` function is designed to invert the order in which the `scales` dict is accessed (`['seq']['7']` instead of `['7']['seq']`).  You can reverse the order of the colorscale using `reversed`.

```python
import colorlover as cl
from IPython.display import HTML
HTML(cl.to_html(cl.scales['7']['seq']['YlOrRd']))
```
![screen shot 2019-01-19 at 8 42 39 am](https://user-images.githubusercontent.com/15064365/51427456-3b11af00-1bc6-11e9-8871-1406383d4b8e.png)

```python
HTML(cl.to_html(list(reversed(cl.scales['7']['seq']['YlOrRd']))))
```
![screen shot 2019-01-19 at 8 43 26 am](https://user-images.githubusercontent.com/15064365/51427463-4f55ac00-1bc6-11e9-9a9c-fd916151d3e7.png)
